name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '13.11.0'
      - run: npm install -g yarn
      - name: yarn install and test
        run: |
          yarn
          yarn lint:js
          yarn lint:styles
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '13.11.0'
      - run: npm install -g yarn
      - name: yarn install and test
        run: |
          yarn
          yarn test:noWatch
